name: Build and push to `builds` branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v2

      - name: Check out builds branch, merge main
        run: |
          git config --global user.email "team@nayya.com"
          git config --global user.name "Nayya"

          git fetch --all
          git checkout builds
          git pull
          git merge --no-ff --no-commit --allow-unrelated-histories main

          git reset HEAD .gitignore
          git checkout -- .gitignore
          git commit -m "merge main"

      - name: Install all dependencies
        run: yarn

      - name: Build
        run: yarn clean && yarn build

      - name: Push to builds
        run: |
          git add .
          git commit -m "new build" || echo "No additional commit needed"
